// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

		public static class WeaponBehaviorFactory
		{
				public static WeaponBehavior GetWeaponBehavior(WeaponBehaviorEnum selectedBehavior)
				{
					switch (selectedBehavior) {
						case WeaponBehaviorEnum.PISTOL:
							return new PistolWeaponBehavior();
						default:
							return new PistolWeaponBehavior();
					}
				}
		}

